package po;

/**
 * Created by Nifury on 2014/10/20.
 */
public enum ReceiptType {
    STOCK_ACCEPT, STOCK_REJECTION, SALE_ACCEPT, SALE_REJECTION, RECEIVE, PAYMENT, CASH, 
    REPORECEIPT, GOODSRECEIPT, SIGNAL
}
