package presentation.RepoUI;

import java.awt.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author zzt
 */
public class GoodsTypePanel extends javax.swing.JPanel {

    /**
     * Creates new form GoodsTypePanel
     */
    public GoodsTypePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GT_navigator = new javax.swing.JToolBar();
        repo_navi = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        rece_navi = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        log_out = new javax.swing.JButton();
        trees_scroll_panel = new javax.swing.JScrollPane();
        tree_panel = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g) {
                super.paintComponent(g); // Do the original draw
                setAntiAliasing(g, true);
                int[] x = new int[10];
                int[] y = new int[10];
                x[0] = nodePanel1.getLocation().x+nodePanel1.getPreferredSize().width/2;
                y[0] = nodePanel1.getLocation().y+nodePanel1.getPreferredSize().width/2;
                g.drawLine(x[0], y[0], 60, 60);

            }

        };
        nodePanel1 = new NodePanel();

        setPreferredSize(new java.awt.Dimension(800, 600));

        GT_navigator.setFloatable(false);
        GT_navigator.setRollover(true);

        repo_navi.setText("库存管理");
        repo_navi.setFocusable(false);
        repo_navi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        repo_navi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        repo_navi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repo_naviActionPerformed(evt);
            }
        });
        GT_navigator.add(repo_navi);
        GT_navigator.add(filler1);

        rece_navi.setText("单据管理");
        rece_navi.setFocusable(false);
        rece_navi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rece_navi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rece_navi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rece_naviActionPerformed(evt);
            }
        });
        GT_navigator.add(rece_navi);
        GT_navigator.add(filler2);

        log_out.setText("退出登录");
        log_out.setFocusable(false);
        log_out.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        log_out.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });
        GT_navigator.add(log_out);

        tree_panel.setPreferredSize(new java.awt.Dimension(700, 700));

        javax.swing.GroupLayout tree_panelLayout = new javax.swing.GroupLayout(tree_panel);
        tree_panel.setLayout(tree_panelLayout);
        tree_panelLayout.setHorizontalGroup(
            tree_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tree_panelLayout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addComponent(nodePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231))
        );
        tree_panelLayout.setVerticalGroup(
            tree_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tree_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nodePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(544, Short.MAX_VALUE))
        );

        trees_scroll_panel.setViewportView(tree_panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trees_scroll_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(GT_navigator, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(GT_navigator, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(trees_scroll_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void repo_naviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repo_naviActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) MainFrame.frame.getContentPane().getLayout();
        card.show(MainFrame.frame.getContentPane(), "main_card");
        MainFrame.tab_pane.setSelectedIndex(2);
    }//GEN-LAST:event_repo_naviActionPerformed

    private void rece_naviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rece_naviActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) MainFrame.frame.getContentPane().getLayout();
        card.show(MainFrame.frame.getContentPane(), "main_card");
        MainFrame.tab_pane.setSelectedIndex(1);
    }//GEN-LAST:event_rece_naviActionPerformed

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) MainFrame.frame.getContentPane().getLayout();
        card.show(MainFrame.frame.getContentPane(), "main_card");
        MainFrame.tab_pane.setSelectedIndex(3);
    }//GEN-LAST:event_log_outActionPerformed

    
    public static final void setAntiAliasing(Graphics g, boolean yesno) {
        Object obj = yesno ? RenderingHints.VALUE_ANTIALIAS_ON
                : RenderingHints.VALUE_ANTIALIAS_OFF;

        ((Graphics2D) g).setRenderingHint(RenderingHints.KEY_ANTIALIASING, obj);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar GT_navigator;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JButton log_out;
    private NodePanel nodePanel1;
    private javax.swing.JButton rece_navi;
    private javax.swing.JButton repo_navi;
    private javax.swing.JPanel tree_panel;
    private javax.swing.JScrollPane trees_scroll_panel;
    // End of variables declaration//GEN-END:variables
}
