package presentation.RepoUI;


import java.awt.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author zzt
 */
public class GoodsListPanel extends javax.swing.JPanel {

    /**
     * Creates new form GoodsListPanel
     */
    public GoodsListPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gL_main = new javax.swing.JPanel();
        goodslist_pane = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        GL_navigator = new javax.swing.JToolBar();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        repo_navi = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        rece_navi = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        log_out = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        update = new javax.swing.JButton();
        goodslist_buttons = new javax.swing.JPanel();
        find = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        add = new javax.swing.JButton();
        detail = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        gl_add = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        more = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addable_type = new javax.swing.JComboBox();
        subscribe = new javax.swing.JButton();
        model = new javax.swing.JTextField();
        back_add = new javax.swing.JButton();
        detailed_table = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        detailed_list_back = new javax.swing.JButton();
        search_panel = new javax.swing.JPanel();
        search_buttons = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ambiguous = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        back = new javax.swing.JButton();
        gl_del = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        more_del = new javax.swing.JButton();
        addable_type_del = new javax.swing.JComboBox();
        subscribe_del = new javax.swing.JButton();
        back_del = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.CardLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "商品名称", "商品id", "数量", "警戒值"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        goodslist_pane.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setHeaderValue("商品名称");
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setHeaderValue("商品id");
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setHeaderValue("数量");
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setHeaderValue("警戒值");
        }

        GL_navigator.setBackground(java.awt.Color.red);
        GL_navigator.setRollover(true);
        GL_navigator.add(filler1);

        repo_navi.setText("库存管理");
        repo_navi.setFocusable(false);
        repo_navi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        repo_navi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        repo_navi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repo_naviActionPerformed(evt);
            }
        });
        GL_navigator.add(repo_navi);
        GL_navigator.add(filler4);

        rece_navi.setText("单据管理");
        rece_navi.setFocusable(false);
        rece_navi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rece_navi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rece_navi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rece_naviActionPerformed(evt);
            }
        });
        GL_navigator.add(rece_navi);
        GL_navigator.add(filler2);

        log_out.setText("退出登录");
        log_out.setFocusable(false);
        log_out.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        log_out.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });
        GL_navigator.add(log_out);
        GL_navigator.add(filler3);

        update.setText("确认修改");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        GL_navigator.add(update);

        find.setText("查询商品");
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });

        delete.setText("删除商品");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        add.setText("增加商品");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        detail.setText("详细列表");
        detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout goodslist_buttonsLayout = new javax.swing.GroupLayout(goodslist_buttons);
        goodslist_buttons.setLayout(goodslist_buttonsLayout);
        goodslist_buttonsLayout.setHorizontalGroup(
            goodslist_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(goodslist_buttonsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(goodslist_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(goodslist_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(add, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(delete, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(find, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(detail))
                .addGap(24, 24, 24))
        );
        goodslist_buttonsLayout.setVerticalGroup(
            goodslist_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(goodslist_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(add)
                .addGap(18, 18, 18)
                .addComponent(delete)
                .addGap(18, 18, 18)
                .addComponent(find)
                .addGap(18, 18, 18)
                .addComponent(detail)
                .addContainerGap())
        );

        jLabel3.setText("注：下表中，商品名称和警戒值可以直接修改，提交修改请点击确认修改进行上传");

        javax.swing.GroupLayout gL_mainLayout = new javax.swing.GroupLayout(gL_main);
        gL_main.setLayout(gL_mainLayout);
        gL_mainLayout.setHorizontalGroup(
            gL_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gL_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GL_navigator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(gL_mainLayout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(goodslist_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(goodslist_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(gL_mainLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gL_mainLayout.setVerticalGroup(
            gL_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gL_mainLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(GL_navigator, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(gL_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gL_mainLayout.createSequentialGroup()
                        .addComponent(goodslist_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gL_mainLayout.createSequentialGroup()
                        .addComponent(goodslist_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );

        add(gL_main, "GL_main");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "商品名称", "商品id", "商品数量", "警戒值"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        jLabel1.setText("可选类型:");

        more.setText("添加商品");
        more.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreActionPerformed(evt);
            }
        });

        jLabel2.setText("型号:");

        addable_type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addable_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addable_typeActionPerformed(evt);
            }
        });

        subscribe.setText("提交");
        subscribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subscribeActionPerformed(evt);
            }
        });

        model.setText("A");
        model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(more)
                        .addGap(118, 118, 118)
                        .addComponent(subscribe))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addable_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(addable_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(more)
                    .addComponent(subscribe))
                .addContainerGap())
        );

        back_add.setText("返回");
        back_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gl_addLayout = new javax.swing.GroupLayout(gl_add);
        gl_add.setLayout(gl_addLayout);
        gl_addLayout.setHorizontalGroup(
            gl_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_addLayout.createSequentialGroup()
                .addGroup(gl_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gl_addLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(back_add))
                    .addGroup(gl_addLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gl_addLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        gl_addLayout.setVerticalGroup(
            gl_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_addLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(back_add)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(gl_add, "gl_add_del");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "商品名称", "商品id", "数量", "警戒值", "最近进价", "最近售价", "平均进价", "历史记录", "可否赠送"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(2).setResizable(false);
            jTable3.getColumnModel().getColumn(3).setResizable(false);
            jTable3.getColumnModel().getColumn(5).setResizable(false);
            jTable3.getColumnModel().getColumn(6).setResizable(false);
            jTable3.getColumnModel().getColumn(7).setResizable(false);
            jTable3.getColumnModel().getColumn(8).setResizable(false);
        }

        jToolBar1.setRollover(true);
        jToolBar1.add(filler5);

        detailed_list_back.setText("返回");
        detailed_list_back.setFocusable(false);
        detailed_list_back.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        detailed_list_back.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        detailed_list_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailed_list_backActionPerformed(evt);
            }
        });
        jToolBar1.add(detailed_list_back);

        javax.swing.GroupLayout detailed_tableLayout = new javax.swing.GroupLayout(detailed_table);
        detailed_table.setLayout(detailed_tableLayout);
        detailed_tableLayout.setHorizontalGroup(
            detailed_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailed_tableLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(669, Short.MAX_VALUE))
            .addGroup(detailed_tableLayout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        detailed_tableLayout.setVerticalGroup(
            detailed_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailed_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(detailed_table, "detailed_list");

        search.setText("查询");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel4.setText("商品信息：");

        ambiguous.setText("模糊查询");
        ambiguous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambiguousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout search_buttonsLayout = new javax.swing.GroupLayout(search_buttons);
        search_buttons.setLayout(search_buttonsLayout);
        search_buttonsLayout.setHorizontalGroup(
            search_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(search)
                .addGap(18, 18, 18)
                .addComponent(ambiguous)
                .addContainerGap())
        );
        search_buttonsLayout.setVerticalGroup(
            search_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_buttonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(search_buttonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(search)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ambiguous))
                .addContainerGap())
        );

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "商品名称", "商品id", "数量", "警戒值"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable4);

        back.setText("返回");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout search_panelLayout = new javax.swing.GroupLayout(search_panel);
        search_panel.setLayout(search_panelLayout);
        search_panelLayout.setHorizontalGroup(
            search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_panelLayout.createSequentialGroup()
                .addGroup(search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(search_panelLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(search_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(search_panelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(back))
                    .addGroup(search_panelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        search_panelLayout.setVerticalGroup(
            search_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(search_panelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search_buttons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        add(search_panel, "search");

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "商品名称", "商品id", "商品数量", "警戒值"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable5.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTable5);

        jLabel5.setText("可选类型:");

        more_del.setText("添加商品");
        more_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                more_delActionPerformed(evt);
            }
        });

        addable_type_del.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addable_type_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addable_type_delActionPerformed(evt);
            }
        });

        subscribe_del.setText("提交");
        subscribe_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subscribe_delActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(more_del)
                        .addGap(118, 118, 118)
                        .addComponent(subscribe_del))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addable_type_del, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addable_type_del, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(more_del)
                    .addComponent(subscribe_del))
                .addContainerGap())
        );

        back_del.setText("返回");
        back_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_delActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gl_delLayout = new javax.swing.GroupLayout(gl_del);
        gl_del.setLayout(gl_delLayout);
        gl_delLayout.setHorizontalGroup(
            gl_delLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_delLayout.createSequentialGroup()
                .addGroup(gl_delLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gl_delLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(back_del))
                    .addGroup(gl_delLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gl_delLayout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        gl_delLayout.setVerticalGroup(
            gl_delLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_delLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(back_del)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(gl_del, "gl_del");
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        CardLayout card = (CardLayout)this.getLayout();
        card.show(this, "gl_add_del");
    }//GEN-LAST:event_addActionPerformed

    private void modelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailActionPerformed
        CardLayout card = (CardLayout)this.getLayout();
        card.show(this, "detailed_list");
    }//GEN-LAST:event_detailActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void repo_naviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repo_naviActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)MainFrame.frame.getContentPane().getLayout();
        card.show(MainFrame.frame.getContentPane(), "main_card");
        MainFrame.tab_pane.setSelectedIndex(2);
    }//GEN-LAST:event_repo_naviActionPerformed

    private void rece_naviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rece_naviActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)MainFrame.frame.getContentPane().getLayout();
        card.show(MainFrame.frame.getContentPane(), "main_card");
        MainFrame.tab_pane.setSelectedIndex(1);
    }//GEN-LAST:event_rece_naviActionPerformed

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_outActionPerformed
        
        CardLayout card = (CardLayout)MainFrame.frame.getContentPane().getLayout();
        card.show(MainFrame.frame.getContentPane(), "log_card");
    }//GEN-LAST:event_log_outActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        CardLayout card = (CardLayout)this.getLayout();
        card.show(this, "gl_del");
    }//GEN-LAST:event_deleteActionPerformed

    private void findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findActionPerformed
        CardLayout card = (CardLayout)this.getLayout();
        card.show(this, "search");
    }//GEN-LAST:event_findActionPerformed

    private void back_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_addActionPerformed
        CardLayout card = (CardLayout)this.getLayout();
        card.show(this, "GL_main");
    }//GEN-LAST:event_back_addActionPerformed

    private void back_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_delActionPerformed
        CardLayout card = (CardLayout)this.getLayout();
        card.show(this, "GL_main");
    }//GEN-LAST:event_back_delActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        CardLayout card = (CardLayout)this.getLayout();
        card.show(this, "GL_main");
    }//GEN-LAST:event_backActionPerformed

    private void detailed_list_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailed_list_backActionPerformed
        CardLayout card = (CardLayout)this.getLayout();
        card.show(this, "GL_main");
    }//GEN-LAST:event_detailed_list_backActionPerformed

    private void moreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moreActionPerformed

    private void subscribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscribeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subscribeActionPerformed

    private void addable_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addable_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addable_typeActionPerformed

    private void ambiguousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambiguousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ambiguousActionPerformed

    private void more_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_more_delActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_more_delActionPerformed

    private void subscribe_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscribe_delActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subscribe_delActionPerformed

    private void addable_type_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addable_type_delActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addable_type_delActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar GL_navigator;
    private javax.swing.JButton add;
    private javax.swing.JComboBox addable_type;
    private javax.swing.JComboBox addable_type_del;
    private javax.swing.JCheckBox ambiguous;
    private javax.swing.JButton back;
    private javax.swing.JButton back_add;
    private javax.swing.JButton back_del;
    private javax.swing.JButton delete;
    private javax.swing.JButton detail;
    private javax.swing.JButton detailed_list_back;
    private javax.swing.JPanel detailed_table;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JButton find;
    private javax.swing.JPanel gL_main;
    private javax.swing.JPanel gl_add;
    private javax.swing.JPanel gl_del;
    private javax.swing.JPanel goodslist_buttons;
    private javax.swing.JScrollPane goodslist_pane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton log_out;
    private javax.swing.JTextField model;
    private javax.swing.JButton more;
    private javax.swing.JButton more_del;
    private javax.swing.JButton rece_navi;
    private javax.swing.JButton repo_navi;
    private javax.swing.JButton search;
    private javax.swing.JPanel search_buttons;
    private javax.swing.JPanel search_panel;
    private javax.swing.JButton subscribe;
    private javax.swing.JButton subscribe_del;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
