package presentation.RepoUI;

import java.util.ArrayList;
import java.util.Vector;

import javax.swing.JTable;
import javax.swing.table.TableModel;

import vo.GoodsModelVO;
import vo.GoodsReceiptVO;
import vo.GoodsVO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author zzt
 */
public class Goods_rece extends javax.swing.JPanel {

    /**
     * Creates new form Goods_rece
     */
	
	GoodsReceiptVO goodsReceiptVO;
	TableModel goods_table_model;
    

    public Goods_rece(GoodsReceiptVO template, TableModel gift_table) {
    	this.goodsReceiptVO = template; 
    	this.goods_table_model = gift_table;
        initComponents();
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	 jLabel1 = new javax.swing.JLabel();
         type = new javax.swing.JLabel();
         jLabel3 = new javax.swing.JLabel();
         date = new javax.swing.JLabel();
         jScrollPane1 = new javax.swing.JScrollPane();
         goodsTable = new javax.swing.JTable();
         jLabel2 = new javax.swing.JLabel();
         user = new javax.swing.JLabel();
         jLabel4 = new javax.swing.JLabel();
         all_money = new javax.swing.JLabel();

         jLabel1.setText("单据名：");

         type.setText("库存赠送单");

         jLabel3.setText("日期：");

         date.setText(goodsReceiptVO.getDate());

         goodsTable.setModel(goods_table_model);
         jScrollPane1.setViewportView(goodsTable);

         jLabel2.setText("用户：");

         user.setText(goodsReceiptVO.getUser());

         jLabel4.setText("总额：");

         all_money.setText(""+goodsReceiptVO.getSumOfGifts());

         javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
         this.setLayout(layout);
         layout.setHorizontalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addGap(88, 88, 88)
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                     .addGroup(layout.createSequentialGroup()
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                             .addComponent(jLabel1)
                             .addComponent(jLabel2))
                         .addGap(18, 18, 18)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                             .addGroup(layout.createSequentialGroup()
                                 .addComponent(user)
                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                 .addComponent(jLabel4))
                             .addGroup(layout.createSequentialGroup()
                                 .addComponent(type)
                                 .addGap(40, 40, 40)
                                 .addComponent(jLabel3)))
                         .addGap(18, 18, 18)
                         .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                             .addComponent(date)
                             .addComponent(all_money))))
                 .addContainerGap(74, Short.MAX_VALUE))
         );
         layout.setVerticalGroup(
             layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
             .addGroup(layout.createSequentialGroup()
                 .addGap(42, 42, 42)
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel1)
                     .addComponent(type)
                     .addComponent(jLabel3)
                     .addComponent(date))
                 .addGap(18, 18, 18)
                 .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel2)
                     .addComponent(user)
                     .addComponent(jLabel4)
                     .addComponent(all_money))
                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                 .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                 .addGap(46, 46, 46))
         );
     }// </editor-fold>                        


    public void set_table_model(TableModel tableModel){
    	goodsTable.setModel(tableModel);
    	this.repaint();
    }
     // Variables declaration - do not modify                     
     private javax.swing.JLabel all_money;
     private javax.swing.JLabel date;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JTable goodsTable;
     private javax.swing.JLabel type;
     private javax.swing.JLabel user;
}
