package presentation.RepoUI;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.HashMap;

import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListDataListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import businesslogic.RepositoryCheckbl.RepoCheckBLImpl;
import businesslogic.RepositoryCheckbl.RepoCheckDataImpl;
import dataservice.RepositoryCheckdataservice.RepoCheckDataService;
import po.GoodsModelPO;
import util.RMIUtility;
import vo.GoodsModelVO;
import vo.GoodsVO;
import businesslogic.GoodsListbl.GL_controller;
import businesslogic.GoodsTypebl.GT_controller;
import businesslogicservice.GoodsTypeblservice.GT_GL_BLservice;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author zzt
 */
public class GoodsListPanel extends javax.swing.JPanel {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form GoodsListPanel
     */
    GL_controller gl_controller;
    GT_GL_BLservice gt_GL_BLservice = null;
    HashMap<String, GoodsModelPO> goodsModels = new HashMap<String, GoodsModelPO>();
    ArrayList<GoodsModelVO> goodsModel_add = new ArrayList<GoodsModelVO>();
    ArrayList<GoodsModelVO> goodsModel_del = new ArrayList<GoodsModelVO>();
    ArrayList<GoodsModelVO> goodsModel_search = new ArrayList<GoodsModelVO>();

    public GoodsListPanel() {
        try {
            gl_controller = new GL_controller();

            goodsModels = gl_controller.getGoodsModelPOs();
        } catch (RemoteException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(MainFrame.frame, e
                    + ": Fail to connect to get goods list");
        } catch (NullPointerException e2) {
            if (MainFrame.DEBUG) {
                e2.printStackTrace();
            } else {
                JOptionPane.showMessageDialog(MainFrame.frame, e2
                        + ": Fail to connect to get goods list");
            }
        } catch (NotBoundException e) {
            e.printStackTrace();
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "rawtypes"})
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gL_main = new javax.swing.JPanel();
        goodslist_pane = new javax.swing.JScrollPane();
        general_table = new javax.swing.JTable();
        GL_navigator = new javax.swing.JToolBar();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0),
                new java.awt.Dimension(20, 0),
                new java.awt.Dimension(20, 32767));
        repo_navi = new javax.swing.JButton();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0),
                new java.awt.Dimension(20, 0),
                new java.awt.Dimension(20, 32767));
        rece_navi = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0),
                new java.awt.Dimension(20, 0),
                new java.awt.Dimension(20, 32767));
        log_out = new javax.swing.JButton();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0),
                new java.awt.Dimension(20, 0),
                new java.awt.Dimension(20, 32767));
        update = new javax.swing.JButton();
        goodslist_buttons = new javax.swing.JPanel();
        find = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        add = new javax.swing.JButton();
        detail = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        gl_add = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        add_table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        more = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addable_type = new javax.swing.JComboBox();
        subscribe = new javax.swing.JButton();
        model = new javax.swing.JTextField();
        de_in = new javax.swing.JLabel();
        de_out = new javax.swing.JLabel();
        default_in = new javax.swing.JTextField();
        default_out = new javax.swing.JTextField();
        goods_name = new javax.swing.JLabel();
        goods_name_field = new javax.swing.JTextField();
        back_add = new javax.swing.JButton();
        detailed_panel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        detailed_table = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0),
                new java.awt.Dimension(20, 0),
                new java.awt.Dimension(20, 32767));
        detailed_list_back = new javax.swing.JButton();
        search_panel = new javax.swing.JPanel();
        search_buttons = new javax.swing.JPanel();
        search = new javax.swing.JButton();
        goods_info_search = new javax.swing.JTextField();
        goods_info_search.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                searchActionPerformed(e);

            }
        });
        jLabel4 = new javax.swing.JLabel();
        ambiguous = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        search_result = new javax.swing.JTable();
        back = new javax.swing.JButton();
        gl_del = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        del_table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        more_del = new javax.swing.JButton();
        type_del = new javax.swing.JComboBox();
        subscribe_del = new javax.swing.JButton();
        back_del = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new java.awt.CardLayout());

        try {
            general_table.setModel(new GL_general_TableModel(goodsModels));
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(MainFrame.frame,
                    "Fail to get goods models");
        }
        general_table.setColumnSelectionAllowed(true);
        general_table.getTableHeader().setReorderingAllowed(false);
        goodslist_pane.setViewportView(general_table);
        general_table
                .getColumnModel()
                .getSelectionModel()
                .setSelectionMode(
                        javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (general_table.getColumnModel().getColumnCount() > 0) {
            general_table.getColumnModel().getColumn(0).setResizable(false);
            general_table.getColumnModel().getColumn(0).setHeaderValue("商品名称");
            general_table.getColumnModel().getColumn(1).setResizable(false);
            general_table.getColumnModel().getColumn(1).setHeaderValue("商品id");
            general_table.getColumnModel().getColumn(2).setResizable(false);
            general_table.getColumnModel().getColumn(2).setHeaderValue("数量");
            general_table.getColumnModel().getColumn(3).setResizable(false);
            general_table.getColumnModel().getColumn(3).setHeaderValue("警戒值");
        }
        general_table.getModel().addTableModelListener(
                new TableModelListener() {

                    @Override
                    public void tableChanged(TableModelEvent e) {
                        int row = e.getFirstRow();
                        int column = e.getColumn();
                        TableModel model = (TableModel) e.getSource();
                        Integer data = (Integer) model.getValueAt(row, 3);
                        String id = (String) model.getValueAt(row, 1);
                        String name = (String) model.getValueAt(row, 0);
                        GoodsVO temp = new GoodsVO(id, name, data);
                        System.out
                                .println("-----------------------------------------------");
                        if (column == 0 && data != null && !data.equals("")) {// name is vaild
                            try {
                                gl_controller.set_signal_name(temp);
                            } catch (Exception e1) {
                                JOptionPane.showMessageDialog(MainFrame.frame,
                                        e1 + " : Fail to update information");
                                e1.printStackTrace();
                            }
                        } else if (column == 3 && data != null
                                && (Integer) data >= 0) {// signal
                            // is
                            // valid
                            try {
                                gl_controller.set_signal_name(temp);
                            } catch (Exception e1) {

                                e1.printStackTrace();
                            }
                        } else {
                            JOptionPane.showMessageDialog(MainFrame.frame,
                                    "Invalid change");
                        }
                    }
                });

        GL_navigator.setBackground(java.awt.Color.red);
        GL_navigator.setRollover(true);
        GL_navigator.add(filler1);

        repo_navi.setText("库存管理");
        repo_navi.setFocusable(false);
        repo_navi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        repo_navi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        repo_navi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repo_naviActionPerformed(evt);
            }
        });
        GL_navigator.add(repo_navi);
        GL_navigator.add(filler4);

        rece_navi.setText("单据管理");
        rece_navi.setFocusable(false);
        rece_navi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rece_navi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rece_navi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rece_naviActionPerformed(evt);
            }
        });
        GL_navigator.add(rece_navi);
        GL_navigator.add(filler2);

        log_out.setText("退出登录");
        log_out.setFocusable(false);
        log_out.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        log_out.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        log_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_outActionPerformed(evt);
            }
        });
        GL_navigator.add(log_out);
        GL_navigator.add(filler3);

        update.setText("刷新数据");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        GL_navigator.add(update);

        find.setText("查询商品");
        find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findActionPerformed(evt);
            }
        });

        delete.setText("删除商品");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        add.setText("增加商品");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        detail.setText("详细列表");
        detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout goodslist_buttonsLayout = new javax.swing.GroupLayout(
                goodslist_buttons);
        goodslist_buttons.setLayout(goodslist_buttonsLayout);
        goodslist_buttonsLayout
                .setHorizontalGroup(goodslist_buttonsLayout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                goodslist_buttonsLayout
                                        .createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(
                                                goodslist_buttonsLayout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(
                                                                goodslist_buttonsLayout
                                                                        .createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(
                                                                                add,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(
                                                                                delete,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(
                                                                                find,
                                                                                javax.swing.GroupLayout.Alignment.TRAILING))
                                                        .addComponent(detail))
                                        .addGap(24, 24, 24)));
        goodslist_buttonsLayout.setVerticalGroup(goodslist_buttonsLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        goodslist_buttonsLayout.createSequentialGroup()
                                .addContainerGap().addComponent(add)
                                .addGap(18, 18, 18).addComponent(delete)
                                .addGap(18, 18, 18).addComponent(find)
                                .addGap(18, 18, 18).addComponent(detail)
                                .addContainerGap()));

        jLabel3.setText("注：下表中，商品名称和警戒值可以直接修改，提交修改请点击刷新数据进行上传");

        javax.swing.GroupLayout gL_mainLayout = new javax.swing.GroupLayout(
                gL_main);
        gL_main.setLayout(gL_mainLayout);
        gL_mainLayout.setHorizontalGroup(gL_mainLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        gL_mainLayout
                                .createSequentialGroup()
                                .addContainerGap()
                                .addComponent(GL_navigator,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE).addContainerGap())
                .addGroup(
                        gL_mainLayout
                                .createSequentialGroup()
                                .addContainerGap(63, Short.MAX_VALUE)
                                .addComponent(goodslist_pane,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        556,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(goodslist_buttons,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                .addGroup(
                        gL_mainLayout
                                .createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3)
                                .addContainerGap(
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));
        gL_mainLayout
                .setVerticalGroup(gL_mainLayout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                gL_mainLayout
                                        .createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(
                                                GL_navigator,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                29,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                57, Short.MAX_VALUE)
                                        .addGroup(
                                                gL_mainLayout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                gL_mainLayout
                                                                        .createSequentialGroup()
                                                                        .addComponent(
                                                                                goodslist_buttons,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(107,
                                                                                107,
                                                                                107))
                                                        .addGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                gL_mainLayout
                                                                        .createSequentialGroup()
                                                                        .addComponent(
                                                                                goodslist_pane,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                416,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(33,
                                                                                33,
                                                                                33)))));

        add(gL_main, "GL_main");

        add_table.setModel(new GL_general_TableModel(goodsModel_add));

        add_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(add_table);

        jLabel1.setText("可选类型:");

        de_in.setText("默认进价:");

        de_out.setText("默认售价:");

        default_in.setText("jTextField1");

        default_out.setText("jTextField2");

        goods_name.setText("商品名称:");

        goods_name_field.setText("jTextField1");
        more.setText("添加商品");
        more.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreActionPerformed(evt);
            }
        });

        jLabel2.setText("型号:");

        try {
            gt_GL_BLservice = new GT_controller();
        } catch (RemoteException e) {
            JOptionPane.showMessageDialog(MainFrame.frame, e
                    + ": Fail to get type info");
            e.printStackTrace();
        } catch (NullPointerException nullPointerException) {
            nullPointerException.printStackTrace();
            JOptionPane.showMessageDialog(MainFrame.frame, nullPointerException
                    + ": Fail to get type info at ");
        } catch (NotBoundException e) {
            e.printStackTrace();
        }
        try {
            addable_type.setModel(new javax.swing.DefaultComboBoxModel(gt_GL_BLservice
                    .addable_type().toArray()));
        } catch (RemoteException e1) {
            JOptionPane.showMessageDialog(MainFrame.frame, e1
                    + ": Fail to get addable type");
        } catch (NullPointerException nullPointerException) {
            JOptionPane.showMessageDialog(MainFrame.frame, nullPointerException
                    + ": Failed to get addable type");
        }

        subscribe.setText("提交");
        subscribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subscribeActionPerformed(evt);
            }
        });

        model.setText("A");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
                jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(more)
                                .addGap(90, 90, 90)
                                .addComponent(subscribe)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(de_in)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(default_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(de_out)
                                                .addGap(18, 18, 18)
                                                .addComponent(default_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(addable_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                                .addComponent(goods_name)
                                                .addGap(18, 18, 18)
                                                .addComponent(goods_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel2)
                                                .addComponent(goods_name)
                                                .addComponent(goods_name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel1)
                                                .addComponent(addable_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(de_in)
                                                .addComponent(default_in, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(de_out)
                                                .addComponent(default_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(more)
                                        .addComponent(subscribe))
                                .addGap(27, 27, 27))
        );

        back_add.setText("返回");
        back_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gl_addLayout = new javax.swing.GroupLayout(
                gl_add);
        gl_add.setLayout(gl_addLayout);
        gl_addLayout
                .setHorizontalGroup(gl_addLayout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                gl_addLayout
                                        .createSequentialGroup()
                                        .addGroup(
                                                gl_addLayout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(
                                                                gl_addLayout
                                                                        .createSequentialGroup()
                                                                        .addGap(27,
                                                                                27,
                                                                                27)
                                                                        .addComponent(
                                                                                back_add))
                                                        .addGroup(
                                                                gl_addLayout
                                                                        .createSequentialGroup()
                                                                        .addGap(85,
                                                                                85,
                                                                                85)
                                                                        .addComponent(
                                                                                jScrollPane2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                572,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(
                                                                gl_addLayout
                                                                        .createSequentialGroup()
                                                                        .addGap(112,
                                                                                112,
                                                                                112)
                                                                        .addComponent(
                                                                                jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(151, Short.MAX_VALUE)));
        gl_addLayout.setVerticalGroup(gl_addLayout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addGroup(
                gl_addLayout
                        .createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(back_add)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 200,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jPanel1,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap()));

        add(gl_add, "gl_add_del");

        detailed_table.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{}, new String[]{"商品名称", "商品id", "数量", "警戒值", "默认进价", "默认售价",
                "最近进价", "最近售价", "平均进价", "历史记录", "可否赠送"}) {
            /**
             *
             */
            private static final long serialVersionUID = 1L;
            Class[] types = new Class[]{java.lang.String.class,
                    java.lang.String.class, java.lang.Integer.class,
                    java.lang.Integer.class, java.lang.Double.class,
                    java.lang.Double.class,
                    java.lang.Double.class,
                    java.lang.Double.class, java.lang.Double.class,
                    java.lang.Boolean.class, java.lang.Boolean.class};
            boolean[] canEdit = new boolean[]{false, false, false, false,
                    false, false, false, false, false, false, false};

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
//		set_detail_data(goodsModels);

        detailed_table.getTableHeader().setReorderingAllowed(false);
//        detailed_table.setPreferredSize(new Dimension(1000, 800));
//        detailed_table.setPreferredScrollableViewportSize(new Dimension(750, 500));
//        jScrollPane3.setPreferredSize(new Dimension(750, 500));
        jScrollPane3.setViewportView(detailed_table);

        if (detailed_table.getColumnModel().getColumnCount() > 0) {
            detailed_table.getColumnModel().getColumn(2).setResizable(false);
            detailed_table.getColumnModel().getColumn(3).setResizable(false);
            detailed_table.getColumnModel().getColumn(5).setResizable(false);
            detailed_table.getColumnModel().getColumn(6).setResizable(false);
            detailed_table.getColumnModel().getColumn(7).setResizable(false);
            detailed_table.getColumnModel().getColumn(8).setResizable(false);
            detailed_table.getColumnModel().getColumn(9).setResizable(false);
            detailed_table.getColumnModel().getColumn(10).setResizable(false);
        }

        jToolBar1.setRollover(true);
        jToolBar1.add(filler5);

        detailed_list_back.setText("返回");
        detailed_list_back.setFocusable(false);
        detailed_list_back
                .setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        detailed_list_back
                .setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        detailed_list_back
                .addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        detailed_list_backActionPerformed(evt);
                    }
                });
        jToolBar1.add(detailed_list_back);

        javax.swing.GroupLayout detailed_tableLayout = new javax.swing.GroupLayout(
                detailed_panel);
        detailed_panel.setLayout(detailed_tableLayout);
        detailed_tableLayout.setHorizontalGroup(detailed_tableLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        detailed_tableLayout
                                .createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jToolBar1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        100,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(669, Short.MAX_VALUE))
                .addGroup(
                        detailed_tableLayout.createSequentialGroup()
                                .addComponent(jScrollPane3).addContainerGap()));
        detailed_tableLayout
                .setVerticalGroup(detailed_tableLayout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                detailed_tableLayout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(
                                                jToolBar1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(
                                                jScrollPane3,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                541, Short.MAX_VALUE)
                                        .addContainerGap()));

        add(detailed_panel, "detailed_list");

        search.setText("查询");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        goods_info_search.setText("jTextField2");

        jLabel4.setText("商品信息：");

        ambiguous.setText("模糊查询");

        javax.swing.GroupLayout search_buttonsLayout = new javax.swing.GroupLayout(
                search_buttons);
        search_buttons.setLayout(search_buttonsLayout);
        search_buttonsLayout.setHorizontalGroup(search_buttonsLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        search_buttonsLayout
                                .createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addGap(29, 29, 29)
                                .addComponent(goods_info_search,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46).addComponent(search)
                                .addGap(18, 18, 18).addComponent(ambiguous)
                                .addContainerGap()));
        search_buttonsLayout
                .setVerticalGroup(search_buttonsLayout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                search_buttonsLayout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                search_buttonsLayout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(search)
                                                        .addComponent(
                                                                goods_info_search,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ambiguous))
                                        .addContainerGap()));

        search_result.setModel(new GL_general_TableModel(goodsModel_search));

        jScrollPane1.setViewportView(search_result);

        back.setText("返回");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout search_panelLayout = new javax.swing.GroupLayout(
                search_panel);
        search_panel.setLayout(search_panelLayout);
        search_panelLayout
                .setHorizontalGroup(search_panelLayout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                search_panelLayout
                                        .createSequentialGroup()
                                        .addGroup(
                                                search_panelLayout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(
                                                                search_panelLayout
                                                                        .createSequentialGroup()
                                                                        .addGap(116,
                                                                                116,
                                                                                116)
                                                                        .addComponent(
                                                                                search_buttons,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(
                                                                search_panelLayout
                                                                        .createSequentialGroup()
                                                                        .addGap(50,
                                                                                50,
                                                                                50)
                                                                        .addComponent(
                                                                                back))
                                                        .addGroup(
                                                                search_panelLayout
                                                                        .createSequentialGroup()
                                                                        .addGap(29,
                                                                                29,
                                                                                29)
                                                                        .addComponent(
                                                                                jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                690,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(89, Short.MAX_VALUE)));
        search_panelLayout
                .setVerticalGroup(search_panelLayout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                search_panelLayout
                                        .createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(back)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(
                                                search_buttons,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(
                                                jScrollPane1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                386,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(72, Short.MAX_VALUE)));

        add(search_panel, "search");

        del_table.setModel(new GL_general_TableModel(goodsModel_del));

        del_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(del_table);

        jLabel5.setText("可选类型:");

        more_del.setText("添加商品");
        more_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                more_delActionPerformed(evt);
            }
        });
        try {
            type_del.setModel(new javax.swing.DefaultComboBoxModel(gl_controller
                    .type_del().toArray()));
        } catch (RemoteException e1) {
            e1.printStackTrace();
        }

        subscribe_del.setText("提交");
        subscribe_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subscribe_delActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
                jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout
                .setHorizontalGroup(jPanel2Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanel2Layout
                                        .createSequentialGroup()
                                        .addGroup(
                                                jPanel2Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(
                                                                jPanel2Layout
                                                                        .createSequentialGroup()
                                                                        .addGap(61,
                                                                                61,
                                                                                61)
                                                                        .addComponent(
                                                                                more_del)
                                                                        .addGap(118,
                                                                                118,
                                                                                118)
                                                                        .addComponent(
                                                                                subscribe_del))
                                                        .addGroup(
                                                                jPanel2Layout
                                                                        .createSequentialGroup()
                                                                        .addGap(106,
                                                                                106,
                                                                                106)
                                                                        .addComponent(
                                                                                jLabel5)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(
                                                                                type_del,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(79, 79, 79)));
        jPanel2Layout
                .setVerticalGroup(jPanel2Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanel2Layout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                jPanel2Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(
                                                                type_del,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(
                                                jPanel2Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(more_del)
                                                        .addComponent(
                                                                subscribe_del))
                                        .addContainerGap()));

        back_del.setText("返回");
        back_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_delActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gl_delLayout = new javax.swing.GroupLayout(
                gl_del);
        gl_del.setLayout(gl_delLayout);
        gl_delLayout
                .setHorizontalGroup(gl_delLayout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                gl_delLayout
                                        .createSequentialGroup()
                                        .addGroup(
                                                gl_delLayout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(
                                                                gl_delLayout
                                                                        .createSequentialGroup()
                                                                        .addGap(36,
                                                                                36,
                                                                                36)
                                                                        .addComponent(
                                                                                back_del))
                                                        .addGroup(
                                                                gl_delLayout
                                                                        .createSequentialGroup()
                                                                        .addGap(85,
                                                                                85,
                                                                                85)
                                                                        .addComponent(
                                                                                jScrollPane4,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                594,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(
                                                                gl_delLayout
                                                                        .createSequentialGroup()
                                                                        .addGap(176,
                                                                                176,
                                                                                176)
                                                                        .addComponent(
                                                                                jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(129, Short.MAX_VALUE)));
        gl_delLayout
                .setVerticalGroup(gl_delLayout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                gl_delLayout
                                        .createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(back_del)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(
                                                jScrollPane4,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                247,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70)
                                        .addComponent(
                                                jPanel2,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap()));

        add(gl_del, "gl_del");
    }// </editor-fold>//GEN-END:initComponents

    private void set_detail_data(HashMap<String, GoodsModelPO> goods) {
        DefaultTableModel detail_model = (DefaultTableModel) detailed_table
                .getModel();
        detail_model.setRowCount(0);
        RepoCheckDataService repoCheckDataService = null;
        try {
            repoCheckDataService = (RepoCheckDataService) RMIUtility.getImpl(RepoCheckBLImpl.check);
        } catch (RemoteException e) {
            e.printStackTrace();
        } catch (NotBoundException e) {
            e.printStackTrace();
        }
        for (String string : goods.keySet()) {
            GoodsModelPO temp = goods.get(string);
            Object[] row = new Object[0];
            try {
                assert repoCheckDataService != null;
                row = new Object[]{temp.getName(), temp.getId(),
                        temp.getAmount(), temp.getSignal(), temp.getDefault_in(), temp.getDefault_out(),
                        temp.getLastInPrice(),
                        temp.getLastOutPrice(), repoCheckDataService.getAver_in(temp.getId()).getObj(),
                        temp.isEverHas(), temp.isGift(),};
            } catch (RemoteException e) {
                e.printStackTrace();
            }
            detail_model.addRow(row);
        }
    }

    private void add_add_del_search_data(JTable table, GoodsModelVO goodsModelVO) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        if (MainFrame.DEBUG) {
            model.addRow(new Object[]{"a", "b", "1", "2"});
        } else {
            model.addRow(new Object[]{goodsModelVO.getName(),
                    goodsModelVO.getId(), goodsModelVO.getAmount(),
                    goodsModelVO.getSignal()});
        }
    }

    private void addActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addActionPerformed
        update("gl_add_del");
    }// GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_updateActionPerformed
        try {

            goodsModels = gl_controller.getGoodsListPO().getGoodsModels();
        } catch (Exception e) {
            JOptionPane
                    .showMessageDialog(MainFrame.frame, "Fail to fetch data");
        }
        if (MainFrame.DEBUG) {
            GoodsModelPO temp = new GoodsModelPO("a1", "light", "A");
            temp.setSignal(20);
            temp.setAmount(30);
            goodsModels.put("a1", temp);
        }

        //update the statistic of gl_main's general table
        general_table.setModel(new GL_general_TableModel(goodsModels));
        //update the statistic of detailed table
        set_detail_data(goodsModels);
        //update the type of del and add
        try {
            type_del.setModel(new javax.swing.DefaultComboBoxModel(gl_controller
                    .type_del().toArray()));
        } catch (RemoteException e) {
            e.printStackTrace();
        }
        try {
            addable_type.setModel(new javax.swing.DefaultComboBoxModel(gt_GL_BLservice
                    .addable_type().toArray()));
        } catch (RemoteException e1) {
            JOptionPane.showMessageDialog(MainFrame.frame, e1
                    + ": Fail to get addable type");
        } catch (NullPointerException nullPointerException) {
            JOptionPane.showMessageDialog(MainFrame.frame, nullPointerException
                    + ": Failed to get addable type");
        }
    }// GEN-LAST:event_updateActionPerformed

    private void detailActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_detailActionPerformed
        CardLayout card = (CardLayout) this.getLayout();
        card.show(this, "detailed_list");
        set_detail_data(goodsModels);
    }// GEN-LAST:event_detailActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_searchActionPerformed

        if (goods_info_search.getText() == null) {
            return;
        }
        if (goods_info_search.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Invaild input");
            return;
        }
        if (ambiguous.isSelected()) {
            String info = goods_info_search.getText();

            if (info.contains(" ")) {
                try {
                    goodsModel_search = gl_controller.iSearch(info.split(" "));
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
            } else {
                try {
                    goodsModel_search = gl_controller.iSearch(info);
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
            }
            if (goodsModel_search == null) {
                JOptionPane.showMessageDialog(null, "Invaild input ");
                return;
            } else if (goodsModel_search.size() == 0) {
                JOptionPane.showMessageDialog(null, "No goods meet your input");
                return;
            }
            search_result
                    .setModel(new GL_general_TableModel(goodsModel_search));
        } else {
            GoodsModelVO temp = null;
            if (MainFrame.DEBUG) {
                temp = new GoodsModelVO("a1", "a1-A", "Light", "A");
            } else {
                try {
                    temp = gl_controller.eSearch_total(goods_info_search.getText());
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
                if (temp == null) {
                    JOptionPane.showMessageDialog(null, "No such goods as id: "
                            + goods_info_search.getText());
                    return;
                }
            }
            ((DefaultTableModel) search_result.getModel()).setRowCount(0);
            goodsModel_add.clear();
            goodsModel_search.add(temp);
            add_add_del_search_data(search_result, temp);
        }
    }// GEN-LAST:event_searchActionPerformed

    private void repo_naviActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_repo_naviActionPerformed

        CardLayout card = (CardLayout) MainFrame.frame.getContentPane()
                .getLayout();
        card.show(MainFrame.frame.getContentPane(), "main_card");
        MainFrame.tab_pane.setSelectedIndex(2);
    }// GEN-LAST:event_repo_naviActionPerformed

    private void rece_naviActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rece_naviActionPerformed
        CardLayout card = (CardLayout) MainFrame.frame.getContentPane()
                .getLayout();
        card.show(MainFrame.frame.getContentPane(), "main_card");
        MainFrame.tab_pane.setSelectedIndex(1);
    }// GEN-LAST:event_rece_naviActionPerformed

    private void log_outActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_log_outActionPerformed

        CardLayout card = (CardLayout) MainFrame.frame.getContentPane()
                .getLayout();
        card.show(MainFrame.frame.getContentPane(), "log_card");
    }// GEN-LAST:event_log_outActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteActionPerformed
        update("gl_del");
    }// GEN-LAST:event_deleteActionPerformed

    private void update(String name) {
//		GoodsListPanel goodsListPanel1 = new GoodsListPanel();
//		MainFrame.frame.getContentPane().add(goodsListPanel1, "goodsList_card");
//		CardLayout card = (CardLayout) MainFrame.frame.getContentPane().getLayout();
//		card.show(MainFrame.frame.getContentPane(), "goodsList_card");
        CardLayout card2 = (CardLayout) this.getLayout();
        card2.show(this, name);
    }

    private void findActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_findActionPerformed
        update("search");
    }// GEN-LAST:event_findActionPerformed

    private void back_addActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_back_addActionPerformed
        updateActionPerformed(evt);
        CardLayout card = (CardLayout) this.getLayout();
        card.show(this, "GL_main");
    }// GEN-LAST:event_back_addActionPerformed

    private void back_delActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_back_delActionPerformed
        back_addActionPerformed(evt);
    }// GEN-LAST:event_back_delActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backActionPerformed
        CardLayout card = (CardLayout) this.getLayout();
        card.show(this, "GL_main");
    }// GEN-LAST:event_backActionPerformed

    private void detailed_list_backActionPerformed(
            java.awt.event.ActionEvent evt) {// GEN-FIRST:event_detailed_list_backActionPerformed
        CardLayout card = (CardLayout) this.getLayout();
        card.show(this, "GL_main");
    }// GEN-LAST:event_detailed_list_backActionPerformed

    static String type_model_seperator = " ";

    private void moreActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_moreActionPerformed
        String add_type = (String) addable_type.getSelectedItem();
        String mo = model.getText();
        double de_in = 0;
        double de_out = 0;
        try {

            de_in = Double.parseDouble(default_in.getText());

            de_out = Double.parseDouble(default_out.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Wrong format of number, your input is: " + default_in.getText() + " and " + default_out.getText());
            e.printStackTrace();
            return;
        }
        String name = goods_name_field.getText();

        GoodsModelVO temp = new GoodsModelVO(add_type, add_type + type_model_seperator + mo, name, mo, de_in, de_out);
        goodsModel_add.add(temp);

        add_add_del_search_data(add_table, temp);
    }// GEN-LAST:event_moreActionPerformed

    private void subscribeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_subscribeActionPerformed
        try {
            gl_controller.add(goodsModel_add);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(MainFrame.frame, e
                    + ": Fail to add for network");
        }
        // clear all data
        ((DefaultTableModel) add_table.getModel()).setRowCount(0);
        goodsModel_add.clear();
    }// GEN-LAST:event_subscribeActionPerformed

    private void more_delActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_more_delActionPerformed
        String all = "ab cd";
        String del_type = "ab";
        String mo = "cd";
        if (MainFrame.DEBUG) {

        } else {
            all = (String) type_del.getSelectedItem();
            del_type = all.split(type_model_seperator)[0];
            mo = all.split(type_model_seperator)[1];
        }
        //TODO add name of goods
        GoodsModelVO temp = new GoodsModelVO(del_type, all, "light", mo);
        goodsModel_del.add(temp);

        add_add_del_search_data(del_table, temp);
    }// GEN-LAST:event_more_delActionPerformed

    private void subscribe_delActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_subscribe_delActionPerformed
        try {
            for (GoodsModelVO goodsModelVO : goodsModel_del) {
                boolean res = gl_controller.delete(goodsModelVO);
                if (!res) {
                    JOptionPane.showMessageDialog(null, "Fail to delete this goods");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(MainFrame.frame, e
                    + ": Fail to delete for network");
        }
        // clear all data
        ((DefaultTableModel) del_table.getModel()).setRowCount(0);
        goodsModel_del.clear();
    }// GEN-LAST:event_subscribe_delActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar GL_navigator;
    private javax.swing.JButton add;
    private javax.swing.JComboBox<String> addable_type;
    private javax.swing.JComboBox<String> type_del;
    private javax.swing.JCheckBox ambiguous;
    private javax.swing.JButton back;
    private javax.swing.JButton back_add;
    private javax.swing.JButton back_del;
    private javax.swing.JButton delete;
    private javax.swing.JButton detail;
    private javax.swing.JButton detailed_list_back;
    private javax.swing.JPanel detailed_panel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JButton find;
    private javax.swing.JPanel gL_main;
    private javax.swing.JPanel gl_add;
    private javax.swing.JPanel gl_del;
    private javax.swing.JPanel goodslist_buttons;
    private javax.swing.JScrollPane goodslist_pane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable general_table;
    private javax.swing.JTable add_table;
    private javax.swing.JTable detailed_table;
    private javax.swing.JTable search_result;
    private javax.swing.JTable del_table;
    private javax.swing.JTextField goods_info_search;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton log_out;
    private javax.swing.JTextField model;
    private javax.swing.JButton more;
    private javax.swing.JButton more_del;
    private javax.swing.JButton rece_navi;
    private javax.swing.JButton repo_navi;
    private javax.swing.JButton search;
    private javax.swing.JPanel search_buttons;
    private javax.swing.JPanel search_panel;
    private javax.swing.JButton subscribe;
    private javax.swing.JButton subscribe_del;
    private javax.swing.JButton update;

    private javax.swing.JLabel de_in;
    private javax.swing.JLabel de_out;
    private javax.swing.JTextField default_in;
    private javax.swing.JTextField default_out;
    private javax.swing.JLabel goods_name;
    private javax.swing.JTextField goods_name_field;
    // End of variables declaration//GEN-END:variables
}
